replicaCount: 2

image:
  repository: zot.soh.re
  name: hey.soh.re
  tag: "v1.0.6"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80
  targetPort: 8080

virtualService:
  hosts:
    - "hey.soh.re"
  gateway:
    name: "http-gateway"
    namespace: "istio-system"

resources: {}

name: webapp

# New section for the external secret
secret:
  enabled: true
  name: my-external-secret  # Name of the existing secret
