replicaCount: 2

image:
  repository: zot.soh.re
  name: hey.soh.re
  tag: "v1.0.6"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80
  targetPort: 8080

resources: {}

name: webapp

# New section for the external secret
secret:
  enabled: false
  name: my-external-secret  # Name of the existing secret

postgres:
  enabled: false
  name: postgres-cluster
  instances: 2
  storage:
    size: 10Gi
  bootstrap:
    initdb:
      database: app
      owner: app

# ConfigMap section - user can define which configmaps to mount
configMaps: []
  # - name: custom-configmap
  #   mountPath: "/var/www/html"
  #   data:
  #     index.php: |
  #       <?php
  #       #$ip = getenv("REMOTE_ADDR");
  #       $ip = getenv('HTTP_X_FORWARDED_FOR');
  #       print 'Your IP is '.$ip.' Want to fight about it?';
  #       echo "\n";
  #       ?>

env: []
  #REPO_URL: jmainguy.com
pvc:
  enabled: false
  size: 1Gi
  mountPath: /data

virtualService:
  hosts:
    - "hey.soh.re"
  #  - "www.hey.soh.re"
  #redirectToPrimary: true    # Redirect www.HOSTNAME to HOSTNAME
