apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Values.name }}-tls
spec:
  secretName: {{ .Values.name }}-tls
  issuerRef:
    name: letsencrypt-http
    kind: ClusterIssuer
  dnsNames:
{{- range .Values.virtualService.hosts }}
    - {{ . }}
{{- end }}
