apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
  labels:
    app: {{ .Values.name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
    spec:
      containers:
        - name: {{ .Values.name }}
          image: "{{ .Values.image.repository }}/{{ .Values.image.name }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- if .Values.secret.enabled }}
          envFrom:
            - secretRef:
                name: {{ .Values.secret.name }}
          {{- end }}

          {{- if .Values.env }}
          env:
            {{- range $key, $value := .Values.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
          {{- end }}

          {{- if .Values.configMaps }}
          volumeMounts:
            {{- range .Values.configMaps }}
            - name: {{ .name }}
              mountPath: {{ .mountPath }}
            {{- end }}
          {{- end }}

          {{- if .Values.pvc.enabled }}
          volumeMounts:
            - name: {{ .Values.name }}-pvc
              mountPath: {{ .Values.pvc.mountPath }}
          {{- end }}

      {{- if .Values.configMaps }}
      volumes:
        {{- range .Values.configMaps }}
        - name: {{ .name }}
          configMap:
            name: {{ .name }}
        {{- end }}
      {{- end }}

      {{- if .Values.pvc.enabled }}
      volumes:
        - name: {{ .Values.name }}-pvc
          persistentVolumeClaim:
            claimName: {{ .Values.name }}-pvc
      {{- end }}
