{{- range .Values.persistence }}
{{- if and .size (not .existingClaim) }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ $.Values.name }}-{{ .name }}-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .size }}
  {{- if .volumeName }}
  volumeName: {{ .volumeName }}
  {{- end }}
{{- end }}
{{- end }}
