apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: {{ .Values.name }}-vs
spec:
  hosts:
{{- range .Values.virtualService.hosts }}
    - {{ . }}
{{- end }}
  gateways:
    - namespace-gateway
  http:
{{- if .Values.virtualService.redirectToPrimary }}
    - match:
        - uri:
            prefix: "/"
          authority:
            regex: "^www\\.(.*)"
      redirect:
        authority: "{{ .Values.virtualService.hosts | first }}"
{{- end }}
    - route:
        - destination:
            host: {{ .Values.name }}
            port:
              number: {{ .Values.service.targetPort }}
